In [10]:
import pandas as pd
import numpy as np
import seaborn as sns 
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
import pymysql
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import silhouette_score, calinski_harabasz_score
from sklearn.metrics import silhouette_score

engine = create_engine(
    "mysql+pymysql://{user}:{pw}@localhost/{db}".format(
        user="root",
        pw="Chikaobi123#",
        db="pandas_archive"
    )
)

In [11]:
df = pd.read_csv(r'C:\Users\User\Downloads\archive\tassi-di-omicidi-globali-per-paese.csv')

In [17]:
df.head()

  iso_code      country  year   sex age_group  homicide_rate
0      AFG  Afghanistan  2009  both       ALL       4.059550
1      AFG  Afghanistan  2010  both       ALL       3.475452
2      AFG  Afghanistan  2011  both       ALL       4.194535
3      AFG  Afghanistan  2012  both       ALL       6.374339
4      AFG  Afghanistan  2015  both       ALL       9.952186

In [13]:
df.shape

(22092, 6)

In [14]:
df.isnull().sum()

iso_code         0
country          0
year             0
sex              0
age_group        0
homicide_rate    0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22092 entries, 0 to 22091
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   iso_code       22092 non-null  object
 1   country        22092 non-null  object
 2   year           22092 non-null  int64
 3   sex            22092 non-null  object
 4   age_group      22092 non-null  object
 5   homicide_rate  22092 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.0+ MB

In [29]:
age_clas = df.groupby('age_group').size()
sex_clas = df.groupby('sex').size()
country_clas = df.groupby('country').size()

In [31]:
wx = [sex_clas,age_clas,country_clas ]

In [32]:
for i in wx:
    print()
    print(i)
    print('-------------')

sex
both      4215
female    8892
male      8985
dtype: int64
-------------

age_group
0_9        1048
10_14      1014
15_17      1076
18_19      1066
20_24      1105
25_29      1147
30_44      1968
45_59      1941
60_PLUS    1941
ALL        9786
dtype: int64
-------------

country
Afghanistan        13
Albania           161
Algeria            84
American Samoa     27
Andorra            84
                 ...
Venezuela          79
Vietnam            11
Yemen              10
Zambia             16
Zimbabwe           26
Length: 201, dtype: int64
-------------

In [36]:
df.describe().style.background_gradient(cmap = 'Blues')

In [39]:
# Best for Jupyter/Colab/VS Code Notebooks
correlation = df[['year', 'homicide_rate']].corr().style.background_gradient(cmap='Blues')
correlation

In [42]:
# 1. Sort by year to ensure calculations are chronological
dff = df.sort_values('year')

# 2. Year-over-Year Change
df['rate_delta'] = df['homicide_rate'].diff()

# 3. Rolling Average (using a 3-year window)
df['moving_avg'] = df['homicide_rate'].rolling(window=3).mean()

# 4. Lag Feature (The rate of the PREVIOUS year)
# This is crucial if you want to use the model to PREDICT next year
df['prev_year_rate'] = df['homicide_rate'].shift(1)

# Drop NaNs created by diff/shift/rolling
df = df.dropna()

print(df.head())

      iso_code     country  year     sex age_group  homicide_rate  rate_delta  \
1600       BHS     Bahamas  1990    both       ALL      16.307627   14.255582
14399      MSR  Montserrat  1990    both       ALL       0.000000  -16.307627
14400      MSR  Montserrat  1990  female       ALL       0.000000    0.000000
14401      MSR  Montserrat  1990    male       ALL       0.000000    0.000000
5803       DNK     Denmark  1990  female       ALL       0.958785    0.958785

       moving_avg  prev_year_rate
1600     6.385726        2.052045
14399    6.119891       16.307627
14400    5.435876        0.000000
14401    0.000000        0.000000
5803     0.319595        0.000000

In [43]:
dff

,iso_code,country,year,sex,age_group,homicide_rate,rate_delta,moving_avg,prev_year_rate
5802,DNK,Denmark,1990,both,ALL,0.797506,-5.838230,5.757062,6.635736
18810,SVN,Slovenia,1990,both,ALL,2.052045,1.254539,3.161763,0.797506
1600,BHS,Bahamas,1990,both,ALL,16.307627,14.255582,6.385726,2.052045
14399,MSR,Montserrat,1990,both,ALL,0.000000,-16.307627,6.119891,16.307627
14400,MSR,Montserrat,1990,female,ALL,0.000000,0.000000,5.435876,0.000000
...,...,...,...,...,...,...,...,...,...
19117,SVN,Slovenia,2023,female,45_59,0.450089,0.221480,0.456530,0.228608
14988,NLD,Netherlands,2023,female,30_44,0.642826,0.192737,0.440507,0.450089
14989,NLD,Netherlands,2023,female,45_59,0.606210,-0.036616,0.566375,0.642826
6094,DNK,Denmark,2023,female,10_14,1.261086,0.654876,0.836707,0.606210
6095,DNK,Denmark,2023,female,15_17,0.000000,-1.261086,0.622432,1.261086